### ISSUE TITLE
The window doesn't show up at all when pressing the colorful button

### ISSUE THREAD

**Issue by apoapostolov** [horvillehoot/DnDj#1]
It isn't clear how to open the window, the button shown below seems clickable but nothing shows up:

![image](https://user-images.githubusercontent.com/4083812/89621973-f4b09d80-d89a-11ea-9302-5de55a88b59a.png)

**Comment by horville-hootenkline** [comment]
Hi, can you post a screenshot of any console errors that show up when you press the button? Thanks.

**Comment by Sunamon** [comment]
![image](https://user-images.githubusercontent.com/65740342/89668598-42c5a100-d89b-11ea-950c-b4716d239df6.png)

**Comment by horville-hootenkline** [comment]
Thanks for this. A function was firing before a flag it needed was ready. I think I've fixed it in the new release (0.0.3). Let me know if you are still having the same problem.

**Comment by apoapostolov** [comment]
Fixed in latest update.
